import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'tertiary-container': '#b2ad7d',
                surface: '#f8f9fa',
                error: '#ba1a1a',
                'tertiary-fixed-dim': '#cdc897',
                'on-primary': '#ffffff',
                background: '#f8f9fa',
                'primary-fixed-dim': '#ffb4ac',
                'inverse-primary': '#ffb4ac',
                'on-background': '#191c1d',
                'inverse-surface': '#2e3132',
                'on-secondary-fixed-variant': '#6d3a00',
                'on-secondary': '#ffffff',
                'secondary-fixed': '#ffdcc2',
                'on-tertiary-fixed': '#1e1c00',
                'surface-container': '#edeeef',
                'surface-bright': '#f8f9fa',
                primary: '#b7131a',
                'outline-variant': '#e4beb9',
                'inverse-on-surface': '#f0f1f2',
                'on-secondary-container': '#623300',
                'secondary-container': '#ff8f06',
                'surface-container-lowest': '#ffffff',
                'surface-container-high': '#e7e8e9',
                'on-surface-variant': '#5b403d',
                'surface-variant': '#e1e3e4',
                'on-error': '#ffffff',
                'surface-tint': '#bb171c',
                'on-surface': '#191c1d',
                'surface-dim': '#d9dadb',
                'primary-container': '#db322f',
                'secondary-fixed-dim': '#ffb77b',
                'error-container': '#ffdad6',
                'on-tertiary-fixed-variant': '#4b4822',
                tertiary: '#636037',
                'tertiary-fixed': '#eae4b1',
                'surface-container-low': '#f3f4f5',
                'on-tertiary-container': '#43411b',
                'primary-fixed': '#ffdad6',
                'on-primary-container': '#fffbff',
                'on-tertiary': '#ffffff',
                'on-secondary-fixed': '#2e1500',
                'on-error-container': '#93000a',
                'on-primary-fixed-variant': '#93000d',
                'on-primary-fixed': '#410002',
                'surface-container-highest': '#e1e3e4',
                outline: '#906f6c',
                secondary: '#8f4e00',
            },
            spacing: {
                base: '8px',
                'container-max': '1280px',
                gutter: '24px',
                sm: '12px',
                md: '24px',
                xl: '80px',
                xs: '4px',
                lg: '48px',
            },
            fontSize: {
                'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'display-lg': ['48px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
            },
        },
    },

    plugins: [forms],
};